### PR TITLE
suutraartha : Apply mo'nusvaraH where ever possible

### PR DESCRIPTION
**Pull request by akarshanbiswas**
Change text such as कर्तुम् शक्यते --->> कर्तुं शक्यते which decreases the file size to some extent [compare म् =म + ् = 2 unicode chars against  ं = 1 Unicode char]

Since the file is huge, I have used a script to do the job. Most of the cases, the script used a logic which is fool proof, however in some cases such as in सावनडुहः ७.१.८२ , प्रक्रिया was not followed with a '+' sign and was changed to anusvara and hence my script got confused:
अनडु आम् ह् + स् [ missing + in between आम् and ह् which was changed to आं ह् ]

 which I have checked and fixed and some more with similar cases.
I believe that the changes need to proofreaded by multiple people before merging.
Thanks to all people involved for this wonderful project.

### CODE REVIEW

**Comment by neeleshb** [comment]
This change is not necessary, it has a high error margin and no clear benefit.

**Comment by akarshanbiswas** [comment]
Actually it had a very low error margin and only in exceptions as mentioned in the PR.
It was just needed to be proofread'ed which I'm doing since Saturday. Here is an example from my local repository.

```
"11021": {
        "sa": "केवलम् एकः वर्णः अस्ति चेत् सः यथा आदिवत् कार्यं करोति, तथैव अन्तवदपि कार्यं करोति। ",
        "sd": "यदि कुत्रचित् शब्दस्य 'आदिवर्णस्य' किमपि कार्यमुक्तमस्ति तत्र यद्यपि तस्मिन् शब्दे एकः एव वर्णः अस्ति, तथापि सः एव आदिवर्णसंज्ञां स्वीकरोति। तथैव,  यदि कुत्रचित् शब्दस्य 'अन्तिमवर्णस्य' किमपि कार्यमुक्तमस्ति तत्र यद्यपि तस्मिन् शब्दे एकः एव वर्णः अस्ति, तथापि सः एव अन्तिमवर्णः ज्ञातव्यः - इति अस्य सूत्रस्य आशयः। यथा -\n\n1. 'अ' (= विष्णुः) इति अकारान्तपुंलिङ्गशब्दः। अस्य तृतीयाद्विवचनस्य रूपसिद्धौ 'अ + भ्याम्' इति स्थिते एकः प्रश्नः आगच्छति - <<सुपि च>> [[7.3.102]] इत्यनेन अङ्गस्य अन्तिम-अकारस्य दीर्घादेशः भवति। परन्तु अत्र अङ्गे केवलम् एकः एव वर्णः अस्ति। तर्हि सः एव अन्तिमवर्णरूपेण स्वीकर्तुं शक्यते वा? (तस्मात् पूर्वं किमपि नास्ति चेत् अयमन्तिमवर्णः कथं स्यात् - इति संशयः।) अस्य उत्तरमनेन सूत्रेण दीयते - यत्र एकः एव वर्णः अस्ति, तत्र सः आदिवर्णवत् अपि कार्यं करोति, अन्तिमवर्णवत् अपि कार्यं करोति। अतः अत्र अनेन <<सुपि च>> [[7.3.102]] इत्यनेन  अकारस्य दीर्घः भवितुमर्हति।\n\n2. 'गुरोः भावः' अस्मिन् अर्थे गुरु-शब्दस्य अण्-प्रत्यये कृते 'गौरव' शब्दः सिद्ध्यति। अत्र प्रत्यये णकारः इत्संज्ञकः अस्ति, अतः केवलम् अकारः एव अवशिष्यते। अयं यद्यपि एकाल्-प्रत्ययः अस्ति, तथापि  <<आद्यन्तवदेकस्मिन्>> [[1.1.21]] इत्यनेन सः आदिवत् अपि कार्यं करोति, अतः <<आद्युदात्तश्च>> [[3.1.3]] इत्यनेन 'गौरव' अस्मिन् शब्दे वकारात् परः अयम् (प्रत्ययस्य आदिभूतः)   अकारः उदात्तसंज्ञकः भवति।                                   \n      \nसामान्यभाषायामेतत् सूत्रं स्पष्टीकर्तुमेकमुदाहरणं दीयते - 'देवदत्तस्य एकः एव पुत्र अस्ति चेत्, स एव ज्येष्ठः, स एव कनिष्ठः '। इत्युक्ते, देवदत्तस्य यदि केवलम एकः एव पुत्रः अस्ति, तर्हि 'रे देवदत्त, तव ज्येष्ठपुत्रः कः' इति पृष्टेऽपि देवदत्तः तस्यैव निर्देशं करोति यस्य सः 'रे देवदत्त, तव कनिष्ठपुत्रः कः' इति पृष्टे करोति। अनेनैव प्रकारेण शब्दे एकः एवः वर्णः अस्ति चेत् सः एव आदिवर्णः, सः एव अन्तिमवर्णः भवति।                                        \n             \nपरिभाषेन्दुशेखरे विषयेऽस्मिन् एका परिभाषा दत्ता अस्ति - <ऽव्यपदेशिवदेकस्मिन्ऽ>। अस्याः परिभाषायाः अर्थः अयम् - कस्यापि पदार्थस्य 'एकस्य भागस्य' दत्तमभिधानमपि सः पदार्थः तदा स्वीकरोति यदा सः पदार्थः स्वयमेकभाग-इत्येव अस्ति। इयं परिभाषा अस्य सूत्रस्यैव अर्थं स्पष्टीकरोति।\n        \n       "
    },
  
```
   

Please note that in the [original/upstream](https://ashtadhyayi.com/sutraani/1/1/21), the line starts with " केवलं एकः वर्णः अस्ति[..]" [anusvara in front of a vowel,];
I was about to fix this in 2nd PR.
Meanwhile on another line, in the upstream "तस्मात् पूर्वम् किमपि नास्ति...; 
    
There are errors like this all over the place.

**Comment by neeleshb** [comment]
केवलं एकः --> केवलम् एकः is perfectly fine.
कर्तुम् शक्यते --> कर्तुं शक्यते is not necessary. The first version is not
wrong, and the file size is not an issue.

Re. "errors all over the place", yes I am aware of this. The reader is
expected to be smart enough to understand these errors and rectify them
before using the sutrartha. Having said that, all the pull requests that
actually fix the error (without adding extra stuff) are most welcome.

**Comment by vvasuki** [comment]
आर्य नीलेश, 

> कर्तुम् शक्यते --> कर्तुं शक्यते is not necessary. The first version is not wrong

Given the style of language used, it may be a good idea to - in fact - consistently undo मोऽनुस्वारः (like all other inter-word sandhis), so that one gets   "भूतकालम् द्योतयितुम् धातोः परः आद्युदात्तः लुङ्-प्रत्ययः भवति । " instead of "भूतकालं द्योतयितुम् धातोः परः आद्युदात्तः लुङ्-प्रत्ययः भवति । " A proper padapATha! This consistency, though unusual considering popular practice, would be nice fit for a vyAkaraNa-site.

**Comment by neeleshb** [comment]
Yes, I totally agree with this suggestion.

**Comment by neeleshb** [comment]
However, I'd also like to add that this may be a little premature at this
point. Or rather, if we do this, we will have to do this often every
few months or so. The sutrartha is written as and when I get time, and it
is hard to ensure these minor consistencies when the majority of the focus
is on trying to explain the sutra with as simple language as possible and
with elaborate examples.

As you correctly noticed, the absence of sandhis across sutrartha is
deliberate, so as to help the beginners as well.

**Comment by akarshanbiswas** [comment]
> so as to help the beginners as well.

If you want to help the beginners, it's better to use the English suutraartha because whoever checking this section will have either some knowledge of grammar or possibly none. And I'm myself a beginner started learning in this pandemic. 

Anyways, nevermind.

**Pull request closed without merging**
