### PR TITLE
Fix typos in sutras 6.3.18 & 6.3.35

### PR DESCRIPTION
**Pull request by vipranarayan14**
Changes:

- Join the split words in sutra text ("s") of sutras 6.3.18 & 6.3.35.
- Update the corresponding transliterations ("e").

References:

- https://archive.org/details/Siddhanta_Kaumudi_English_Translation-SC_Vasu/SiddhantaKaumudiEngTranslationScVasuVolume1-1906/page/n492/mode/1up
- https://archive.org/details/Siddhanta_Kaumudi_English_Translation-SC_Vasu/SiddhantaKaumudiEngTranslationScVasuVolume1-1906/page/n570/mode/1up

### CODE REVIEW

**Comment by vipranarayan14** [comment]
@neeleshb sir,

The typo in sutra 6.3.35, is also seen in many other places as show below. Shall I correct them too?

image

**Comment by neeleshb** [comment]
yeah you can do a bulk replace for this sutra text.  The split version isn't necessarily wrong in the description, but it is always better to adhere to the exact structure when it comes to quoting the sutras.

**Comment by vipranarayan14** [comment]
Okay, sir. I will do that and send another PR.

**Comment by vipranarayan14** [comment]
Unrelated: I had sent you a mail regarding license for ashtadyayi.com data. Just informing you in case you didn't notice it, sir.

**Pull request merged**
