### PR TITLE
programmatic fix of kashika_nyaas sutra references

### PR DESCRIPTION
**Pull request by hrishikeshrt**
I programmatically detected 11587 total references to sutras in the kashika_nyaas part.
For this, I pattern matched the text within grave quotes followed by a typical sutra  reference (e.g `[[1|1|111]]`)
I then string matched it in the reverse sutra index, and collected top match (using edit distance similarity), and if the similarity is above a certain threshold and sutra reference from the text is not the same as one found by this match, replaced that.

Out of this, 6938 were correct references, 2903 were incorrect references, for 1746 references there was no sutra match
Of these, I used very strict filtering (threshold = 1, i.e. full text match)
With this, I corrected 1477 bad sutra references and 4042 formatting fixes of already correct sutra references.

I am in the process of manually verifying some more sutras in threshold of 0.95 to 1.

Potential changes are listed in the file attached
[changes_kashika_nyaas.xlsx](https://github.com/ashtadhyayi-com/data/files/5151105/changes_kashika_nyaas.xlsx)

### CODE REVIEW

**Comment by hrishikeshrt** [comment]
manually verified 868 more references to sutras
[changes_kashika_nyaas.xlsx](https://github.com/ashtadhyayi-com/data/files/5152482/changes_kashika_nyaas.xlsx)

**Comment by hrishikeshrt** [comment]
also fixed anuswara usage (e.g. `संज्ञायाम्` --> `सञ्ज्ञायाम्`, `द्वंद्वे` --> `द्वन्द्वे` etc)

**Comment by hrishikeshrt** [comment]
Reverted all anuswara changes.
As per my knowledge, it was always proper to write without anuswara when a vargeeya vyanjana follows, but it seems like I am missing some important point why most of the sutrapatha are following a certain way. I will try to read up regarding that.

**Comment by neeleshb** [comment]
On Tue, Sep 1, 2020 at 11:10 AM Hrishikesh <notifications@github.com> wrote:

> Reverted all anuswara changes.
> As per my knowledge, it was always proper to write without anuswara when a
> vargeeya vyanjana follows, but it seems like I am missing some important
> point why most of the sutrapatha are following a certain way. I will try to
> read up regarding that.
>

That is correct when anuswara does not occur at the end of a पद. But when
anuswara occurs at the end of  पद,  it can remain as anuswaar. See वा
पदान्तस्य https://ashtadhyayi.com/sutraani/8/4/59
All upasargas are पदानि, and hence it is acceptable to retain anuswar at
the end of those.  And therefore, संज्ञा and सञ्ज्ञा are both correct.
However traditionally the books always write it as संज्ञा in the sutra
text. This could be due to simple writing convention (or copying from
manuscripts).  Anyway, we should follow what the traditional books do,
especially when it comes to writing the sutra texts. For other cases (like
your own sentences) you are free to choose either of the ways.

Neelesh

**Comment by hrishikeshrt** [comment]
Thank you for helping me understand. I have reverted all the changes.
So, are the changes like `द्वंद्व` --> `द्वन्द्व` are still valid? 
I will try to modify the logic for fixing anuswara.

**Comment by neeleshb** [comment]
Even for द्वन्द्व and सङ्घ, the versions with anuswara are valid. (द्वंद्व
and संघ). The reason is same - द्वम् and सम् are padas there. However the
books write these with the परसवर्ण, so I said that these two are correct
changes. I don't know
why this special treatment for these words. But when it comes to the sutra
text, we should just follow what the traditional / well known books have
been doing.

**Comment by neeleshb** [comment]
very nice work. Thanks a lot.

**Pull request merged**
