### PR TITLE
 Anuvritti from 13029 to 14007

### PR DESCRIPTION
**Pull request by r-jera**

### CODE REVIEW

**Comment by neeleshb** [comment]
the कर्तरि word from 1.3.14 is not taken ahead as anuvrutti anywhere till शेषात्कर्तरि परस्मैपदम् ।  भावकर्मणोः gives आत्मनेपदम् in भावे and कर्मणि, so everywhere else it automatically falls back to कर्तरि ।  Kashika clarifies this - कर्तृग्रहणम् उत्तरार्थम् शेषात् कर्तरि परस्मैपदम् इति । The कर्तरि word from this sutra is indeed taken as anuvrutti in 1.3.78 onwards (which means there will be 2 कर्तरि there).  But till 1.3.78 we do not need to carry this कर्तरि anywhere.

**Comment by r-jera** [comment]
All books seem to suggest that कर्तरि from  1.3.14 is available till
1.3.93(even if is not used till 1.3.78). Should I leave it that way? Or
should I explicitly remove it till 1.3.78 ?

**Comment by neeleshb** [comment]
Lets remove it till 1.3.77 as the commentary can be considered more
authentic than the general sutrapaatha books. (We should retain it from
1.3.78 till end of the paad).

**Comment by r-jera** [comment]
Done

**Pull request merged**
